default: &default
  adapter: posgrestsql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postges
  password: deinekomisha
  host: localhost
  porrt: 5432

development:
  <<: *default
  database: watch_shop_devvelopment

test:
  <<: *default
  database: watch_shop_test
